version: '3.8'

services:
  ingress:
    image: nginx:alpine
    container_name: logistics_ingress_dev
    ports:
      - '8081:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - host-app
      - login-app
      - dashboard-app
      - ui-library
      - backend-api

  host-app:
    image: logistics_host_app_dev_image
    build:
      context: ../mf-logistics-host-app
    container_name: logistics_host_app_dev
    ports:
      - '3000:80'
    env_file:
      - .env.local

  login-app:
    image: logistics_login_app_dev_image
    build:
      context: ../mf-logistics-login-app
    container_name: logistics_login_app_dev
    ports:
      - '3001:80'
    env_file:
      - .env.local

  dashboard-app:
    image: logistics_dashboard_app_dev_image
    build:
      context: ../mf-logistics-dashboard-app
    container_name: logistics_dashboard_app_dev
    ports:
      - '3004:80'
    env_file:
      - .env.local

  ui-library:
    image: logistics_ui_library_dev_image
    build:
      context: ../mf-logistics-ui-library
    container_name: logistics_ui_library_dev
    ports:
      - '3003:80'
      - '6010:80'

  backend-api:
    image: logistics_backend_api_dev_image
    build:
      context: ../backend-api
      target: builder
    container_name: logistics_backend_api_dev
    command: sh -c "CI=true pnpm install && npx prisma generate && npx prisma migrate deploy && pnpm run start:dev"
    ports:
      - '3005:3000'
    volumes:
      - ../backend-api:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: warehousedb_dev
    environment:
      POSTGRES_USER: warehouseuser
      POSTGRES_PASSWORD: warehousepass
      POSTGRES_DB: warehousedb
    ports:
      - '5433:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U warehouseuser -d warehousedb']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_dev:
